/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadGrupo37.vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import universidadGrupo37.entidades.Alumno;

/**
 *
 * @author crist
 */
public class GestiondeAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestiondeAlumnos
     */
    public GestiondeAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLtitulo = new javax.swing.JLabel();
        JLdni = new javax.swing.JLabel();
        JTFdni = new javax.swing.JTextField();
        JLnombre = new javax.swing.JLabel();
        JLapellido = new javax.swing.JLabel();
        JLestado = new javax.swing.JLabel();
        JTFnombre = new javax.swing.JTextField();
        JTFapellido = new javax.swing.JTextField();
        RBestado = new javax.swing.JRadioButton();
        JLfechanac = new javax.swing.JLabel();
        JDCnacimiento = new com.toedter.calendar.JDateChooser();
        JBbuscar = new javax.swing.JButton();
        JBnuevo = new javax.swing.JButton();
        JBguardar = new javax.swing.JButton();
        JBeliminar = new javax.swing.JButton();
        JBsalir = new javax.swing.JButton();

        JLtitulo.setText("Alumno");

        JLdni.setText("Documento:");

        JLnombre.setText("Nombre:");

        JLapellido.setText("Apellido:");

        JLestado.setText("Estado:");

        JLfechanac.setText("Fecha de Nacimiento:");

        JBbuscar.setText("Buscar");
        JBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbuscarActionPerformed(evt);
            }
        });

        JBnuevo.setText("Nuevo");
        JBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnuevoActionPerformed(evt);
            }
        });

        JBguardar.setText("Guardar");
        JBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBguardarActionPerformed(evt);
            }
        });

        JBeliminar.setText("Eliminar");
        JBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBeliminarActionPerformed(evt);
            }
        });

        JBsalir.setText("Salir");
        JBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JLestado)
                        .addGap(64, 64, 64)
                        .addComponent(RBestado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBguardar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLtitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(JLdni)
                                        .addGap(36, 36, 36))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(JLnombre)
                                        .addGap(55, 55, 55))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(JLapellido)
                                        .addGap(55, 55, 55)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFdni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBbuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBnuevo, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JLfechanac)
                        .addGap(18, 18, 18)
                        .addComponent(JDCnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBsalir)
                            .addComponent(JBeliminar))))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLtitulo)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLdni)
                            .addComponent(JTFdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBbuscar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLnombre)
                            .addComponent(JTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBnuevo))
                        .addGap(18, 18, 18)
                        .addComponent(JLapellido))
                    .addComponent(JTFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLestado)
                            .addComponent(RBestado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JBguardar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLfechanac)
                    .addComponent(JDCnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBeliminar))
                .addGap(34, 34, 34)
                .addComponent(JBsalir)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbuscarActionPerformed
        // TODO add your handling code here:
        if (JTFdni.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "El campo Documento no puede estar vacio");
        }else{
            try {
                int dni = Integer.parseInt(JTFdni.getText());
                Alumno alu= Menu.alumnodata.buscarAlumnoPorDni(dni);
                if(alu != null){
                    JOptionPane.showMessageDialog(null, "" + alu.toString());
                }else{
                    JOptionPane.showMessageDialog(null, "No se encontro el DNI en la base de datos");
                }   
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Ingrese el DNI correctamente");
            }
        }
    }//GEN-LAST:event_JBbuscarActionPerformed

    private void JBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnuevoActionPerformed
        // TODO add your handling code here:
        JTFnombre.setText("");
        JTFapellido.setText("");
        JTFdni.setText("");
        RBestado.setSelected(false);
        JDCnacimiento.setDate(null);
    }//GEN-LAST:event_JBnuevoActionPerformed

    private void JBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBguardarActionPerformed
        // TODO add your handling code here:
        if(JTFapellido.getText().isEmpty() || JTFdni.getText().isEmpty() || JTFnombre.getText().isEmpty() || JDCnacimiento.toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        }else{
            try {
                String nombre = JTFnombre.getText();
                String apellido = JTFapellido.getText();
                int dni = Integer.parseInt(JTFdni.getText());
                LocalDate fechaNac = JDCnacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                boolean estado = RBestado.isSelected();
                
                Alumno alu = new Alumno(dni,apellido,nombre,fechaNac,estado);
                //Buscamos si el dni ya esta en la base de datos
                Alumno aux = Menu.alumnodata.buscarAlumnoPorDni(dni);
                
                if(aux == null){
                    Menu.alumnodata.guardadAlumno(alu);
                }else{
                  JOptionPane.showMessageDialog(null, "El DNI ya esta en la base de datos");  
                }
                JTFnombre.setText("");
                JTFapellido.setText("");
                JTFdni.setText("");
                RBestado.setSelected(false);
                JDCnacimiento.setDate(null);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese los campos correctamente");  
            }
        }
    }//GEN-LAST:event_JBguardarActionPerformed

    private void JBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBeliminarActionPerformed
        // TODO add your handling code here:
        if(JTFdni.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "El campo Documento no puede estar vacio");
        }else{
            try {
                int dni = Integer.parseInt(JTFdni.getText());
                int id = Menu.alumnodata.buscarAlumnoPorDni(dni).getIdAlumno();
                int eleccion = JOptionPane.showConfirmDialog(null, "¿Estas seguro/a de eliminar el alumno?","", JOptionPane.YES_NO_OPTION);
                if(eleccion == JOptionPane.YES_OPTION){
                    Menu.alumnodata.eliminarAlumno(id);
                }else{
                    JOptionPane.showMessageDialog(null, "No se elimino al alumno");
                }
                JTFnombre.setText("");
                JTFapellido.setText("");
                JTFdni.setText("");
                RBestado.setSelected(false);
                JDCnacimiento.setDate(null);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null,"Ingrese el DNI correctamente");
            }
        }
    }//GEN-LAST:event_JBeliminarActionPerformed

    private void JBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JBsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBbuscar;
    private javax.swing.JButton JBeliminar;
    private javax.swing.JButton JBguardar;
    private javax.swing.JButton JBnuevo;
    private javax.swing.JButton JBsalir;
    private com.toedter.calendar.JDateChooser JDCnacimiento;
    private javax.swing.JLabel JLapellido;
    private javax.swing.JLabel JLdni;
    private javax.swing.JLabel JLestado;
    private javax.swing.JLabel JLfechanac;
    private javax.swing.JLabel JLnombre;
    private javax.swing.JLabel JLtitulo;
    private javax.swing.JTextField JTFapellido;
    private javax.swing.JTextField JTFdni;
    private javax.swing.JTextField JTFnombre;
    private javax.swing.JRadioButton RBestado;
    // End of variables declaration//GEN-END:variables
}
