/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadGrupo37.vistas;

import javax.swing.JOptionPane;
import universidadGrupo37.entidades.Materia;

/**
 *
 * @author crist
 */
public class GestiondeMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestiondeMaterias
     */
    public GestiondeMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLtitulo = new javax.swing.JLabel();
        JLid = new javax.swing.JLabel();
        JLnombre = new javax.swing.JLabel();
        JLaño = new javax.swing.JLabel();
        JLestado = new javax.swing.JLabel();
        JTFid = new javax.swing.JTextField();
        JTFnombre = new javax.swing.JTextField();
        JTFanio = new javax.swing.JTextField();
        RBestado = new javax.swing.JRadioButton();
        JBbuscar = new javax.swing.JButton();
        JBnuevo = new javax.swing.JButton();
        JBeliminar = new javax.swing.JButton();
        JBguardar = new javax.swing.JButton();
        JBsalir = new javax.swing.JButton();

        JLtitulo.setText("Materia");

        JLid.setText("Codigo:");

        JLnombre.setText("Nombre:");

        JLaño.setText("Año:");

        JLestado.setText("Estado:");

        JBbuscar.setText("Buscar");
        JBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbuscarActionPerformed(evt);
            }
        });

        JBnuevo.setText("Nuevo");
        JBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnuevoActionPerformed(evt);
            }
        });

        JBeliminar.setText("Eliminar");
        JBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBeliminarActionPerformed(evt);
            }
        });

        JBguardar.setText("Guardar");
        JBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBguardarActionPerformed(evt);
            }
        });

        JBsalir.setText("Salir");
        JBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(JLtitulo))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLnombre)
                            .addComponent(JLid)
                            .addComponent(JLaño)
                            .addComponent(JLestado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(96, Short.MAX_VALUE)
                        .addComponent(JBnuevo)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBestado)
                    .addComponent(JTFanio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JTFid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBbuscar))
                        .addComponent(JTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBeliminar)
                        .addGap(18, 18, 18)
                        .addComponent(JBguardar)
                        .addGap(18, 18, 18)
                        .addComponent(JBsalir)))
                .addGap(0, 138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLtitulo)
                        .addGap(48, 48, 48)
                        .addComponent(JLid))
                    .addComponent(JTFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBbuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLnombre)
                    .addComponent(JTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLaño)
                    .addComponent(JTFanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLestado)
                    .addComponent(RBestado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBnuevo)
                    .addComponent(JBeliminar)
                    .addComponent(JBguardar)
                    .addComponent(JBsalir))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbuscarActionPerformed
        // TODO add your handling code here:
        if(JTFid.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "El campo Codigo no puede estar vacio");
        }else{
            try {
                int idMat = Integer.parseInt(JTFid.getText());
                Materia mat = Menu.materiadata.buscarMateria(idMat);
                if(mat != null){
                    JOptionPane.showMessageDialog(null, "" + mat.toString());
                }else{
                    JOptionPane.showMessageDialog(null, "No se encontro el Codigo en la base de datos");
                }
                JTFid.setText("");
                JTFanio.setText("");
                JTFnombre.setText("");
                RBestado.setSelected(false);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese el Codigo correctamente");
            }
        }
    }//GEN-LAST:event_JBbuscarActionPerformed

    private void JBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnuevoActionPerformed
        // TODO add your handling code here:
        JTFid.setText("");
        JTFanio.setText("");
        JTFnombre.setText("");
        RBestado.setSelected(false);
    }//GEN-LAST:event_JBnuevoActionPerformed

    private void JBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBeliminarActionPerformed
        // TODO add your handling code here:
        if(JTFid.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "El campo Codigo no puede estar vacio");
        }else{
            try {
                int idMat = Integer.parseInt(JTFid.getText());
                int eleccion = JOptionPane.showConfirmDialog(null, "¿Estas seguro/a de eliminar la materia?","", JOptionPane.YES_NO_OPTION);
                if(eleccion == JOptionPane.YES_OPTION){
                    Menu.materiadata.eliminarMateria(idMat);
                }else{
                    JOptionPane.showMessageDialog(null, "No se elimino la materia");
                }
                JTFid.setText("");
                JTFanio.setText("");
                JTFnombre.setText("");
                RBestado.setSelected(false);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null,"Ingrese el Codigo correctamente");
            }
        }        
    }//GEN-LAST:event_JBeliminarActionPerformed

    private void JBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBguardarActionPerformed
        // TODO add your handling code here:
        if(JTFanio.getText().isEmpty() || JTFnombre.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Debe llenar todos los campos menos codigo"); 
        }else{

            try {
                int idMat;
                if(JTFid.getText().isEmpty()){
                    idMat = 0;
                }else{
                    idMat = Integer.parseInt(JTFid.getText());
                }
                String nombre = JTFnombre.getText();    //obtener el nombre de la materia
                int anio = Integer.parseInt(JTFanio.getText()); //obtener el año
                boolean estado = RBestado.isSelected();
                Materia mat = new Materia(nombre, anio, estado);
                if(idMat == 0){
                    Menu.materiadata.guardarMateria(mat);
                }else{
                   Materia aux = Menu.materiadata.buscarMateria(idMat); //Busco si el codigo ya esta en la base de datos
                    if(aux ==null){// si no esta
                        Menu.materiadata.guardarMateria(mat);
                    }else{// si ya esta
                    mat.setIdMateria(idMat);
                    Menu.materiadata.modificarMateria(mat);
                    }
                }
                JTFid.setText("");
                JTFanio.setText("");
                JTFnombre.setText("");
                RBestado.setSelected(false);                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese los campos correctamente");  
            }
        }
    }//GEN-LAST:event_JBguardarActionPerformed

    private void JBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JBsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBbuscar;
    private javax.swing.JButton JBeliminar;
    private javax.swing.JButton JBguardar;
    private javax.swing.JButton JBnuevo;
    private javax.swing.JButton JBsalir;
    private javax.swing.JLabel JLaño;
    private javax.swing.JLabel JLestado;
    private javax.swing.JLabel JLid;
    private javax.swing.JLabel JLnombre;
    private javax.swing.JLabel JLtitulo;
    private javax.swing.JTextField JTFanio;
    private javax.swing.JTextField JTFid;
    private javax.swing.JTextField JTFnombre;
    private javax.swing.JRadioButton RBestado;
    // End of variables declaration//GEN-END:variables
}
