/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universidadGrupo37.vistas;

import universidadGrupo37.accesoADatos.AlumnoData;
import universidadGrupo37.accesoADatos.InscripcionData;
import universidadGrupo37.accesoADatos.MateriaData;

/**
 *
 * @author crist
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public static AlumnoData alumnodata;
    public static MateriaData materiadata;
    public static InscripcionData inscripciondata;
    public Menu() {
        initComponents();
        this.alumnodata = new AlumnoData();
        this.materiadata = new MateriaData();
        this.inscripciondata = new InscripcionData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDPescritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMalumno = new javax.swing.JMenu();
        JMIformAlumno = new javax.swing.JMenuItem();
        JMmateria = new javax.swing.JMenu();
        JMIformMateria = new javax.swing.JMenuItem();
        JMadmin = new javax.swing.JMenu();
        JMImanejoIns = new javax.swing.JMenuItem();
        JMImanejoNotas = new javax.swing.JMenuItem();
        JMconsulta = new javax.swing.JMenu();
        JMIalumnosMat = new javax.swing.JMenuItem();
        JMsalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JDPescritorioLayout = new javax.swing.GroupLayout(JDPescritorio);
        JDPescritorio.setLayout(JDPescritorioLayout);
        JDPescritorioLayout.setHorizontalGroup(
            JDPescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );
        JDPescritorioLayout.setVerticalGroup(
            JDPescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        JMalumno.setText("Alumno");

        JMIformAlumno.setText("Formulario de Alumno");
        JMIformAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIformAlumnoActionPerformed(evt);
            }
        });
        JMalumno.add(JMIformAlumno);

        jMenuBar1.add(JMalumno);

        JMmateria.setText("Materia");

        JMIformMateria.setText("Formulario de Materia");
        JMIformMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIformMateriaActionPerformed(evt);
            }
        });
        JMmateria.add(JMIformMateria);

        jMenuBar1.add(JMmateria);

        JMadmin.setText("Admininistración");

        JMImanejoIns.setText("Manejo de Inscripciones");
        JMImanejoIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMImanejoInsActionPerformed(evt);
            }
        });
        JMadmin.add(JMImanejoIns);

        JMImanejoNotas.setText("Manipulacion de Notas");
        JMImanejoNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMImanejoNotasActionPerformed(evt);
            }
        });
        JMadmin.add(JMImanejoNotas);

        jMenuBar1.add(JMadmin);

        JMconsulta.setText("Consultas");

        JMIalumnosMat.setText("Alumnos por Materia");
        JMIalumnosMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIalumnosMatActionPerformed(evt);
            }
        });
        JMconsulta.add(JMIalumnosMat);

        jMenuBar1.add(JMconsulta);

        JMsalir.setText("Salir");
        JMsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMsalirMouseClicked(evt);
            }
        });
        JMsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMsalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(JMsalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDPescritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JDPescritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMIformAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIformAlumnoActionPerformed
        // TODO add your handling code here:
        GestiondeAlumnos gestionAlu = new GestiondeAlumnos();
        JDPescritorio.removeAll();
        JDPescritorio.repaint();
        gestionAlu.setVisible(true);
        JDPescritorio.add(gestionAlu);
        JDPescritorio.moveToFront(gestionAlu);
    }//GEN-LAST:event_JMIformAlumnoActionPerformed

    private void JMsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMsalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JMsalirActionPerformed

    private void JMIformMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIformMateriaActionPerformed
        // TODO add your handling code here:
        GestiondeMaterias gestionMat = new GestiondeMaterias();
        JDPescritorio.removeAll();
        JDPescritorio.repaint();
        gestionMat.setVisible(true);
        JDPescritorio.add(gestionMat);
        JDPescritorio.moveToFront(gestionMat);
    }//GEN-LAST:event_JMIformMateriaActionPerformed

    private void JMImanejoInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMImanejoInsActionPerformed
        // TODO add your handling code here:
        FormulariodeInscripciones formularioIns = new FormulariodeInscripciones();
        JDPescritorio.removeAll();
        JDPescritorio.repaint();
        formularioIns.setVisible(true);
        JDPescritorio.add(formularioIns);
        JDPescritorio.moveToFront(formularioIns);
    }//GEN-LAST:event_JMImanejoInsActionPerformed

    private void JMImanejoNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMImanejoNotasActionPerformed
        // TODO add your handling code here:
        ActualizaciondeNotas actualizarNota = new ActualizaciondeNotas();
        JDPescritorio.removeAll();
        JDPescritorio.repaint();
        actualizarNota.setVisible(true);
        JDPescritorio.add(actualizarNota);
        JDPescritorio.moveToFront(actualizarNota);
    }//GEN-LAST:event_JMImanejoNotasActionPerformed

    private void JMIalumnosMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIalumnosMatActionPerformed
        // TODO add your handling code here:
        ConsultadeAlumnosporMateria consultasAluMate = new ConsultadeAlumnosporMateria();
        JDPescritorio.removeAll();
        JDPescritorio.repaint();
        consultasAluMate.setVisible(true);
        JDPescritorio.add(consultasAluMate);
        JDPescritorio.moveToFront(consultasAluMate);
        
    }//GEN-LAST:event_JMIalumnosMatActionPerformed

    private void JMsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMsalirMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JMsalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDPescritorio;
    private javax.swing.JMenuItem JMIalumnosMat;
    private javax.swing.JMenuItem JMIformAlumno;
    private javax.swing.JMenuItem JMIformMateria;
    private javax.swing.JMenuItem JMImanejoIns;
    private javax.swing.JMenuItem JMImanejoNotas;
    private javax.swing.JMenu JMadmin;
    private javax.swing.JMenu JMalumno;
    private javax.swing.JMenu JMconsulta;
    private javax.swing.JMenu JMmateria;
    private javax.swing.JMenu JMsalir;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
